# Generated by Django 4.0.5 on 2022-07-06 09:09

from django.db import migrations, models
import package.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('photos', 'Photos'), ('videos', 'Videos'), ('combos', 'Combos')], default='photos', max_length=10)),
                ('img', models.ImageField(upload_to=package.models.generate_filename)),
                ('package_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(default='100', max_length=200)),
                ('photographer', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
