# Generated by Django 4.0.5 on 2022-07-06 09:54

from django.db import migrations, models
import package.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(null=True, upload_to=package.models.generate_filename),
        ),
    ]
