# Generated by Django 4.0.5 on 2022-07-01 19:51

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=teams.models.generate_filename)),
                ('name', models.CharField(max_length=500, null=True)),
                ('designation', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
