# Generated by Django 4.0.5 on 2022-07-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf_name', models.CharField(max_length=250, null=True)),
                ('bl_name', models.CharField(max_length=250, null=True)),
                ('gf_name', models.CharField(max_length=250, null=True)),
                ('gl_name', models.CharField(max_length=250, null=True)),
                ('wedding_dates', models.DateTimeField(null=True)),
                ('event_details', models.TextField()),
                ('venue', models.TextField()),
                ('c_number', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('story', models.TextField()),
                ('thoughts', models.TextField()),
            ],
        ),
    ]
