# Generated by Django 4.0.5 on 2022-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='wedding_dates',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
