# Generated by Django 4.0.5 on 2022-07-01 09:25

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, default='#!', null=True)),
                ('img', models.ImageField(upload_to=image.models.generate_filename)),
            ],
        ),
    ]
