# Generated by Django 4.0.5 on 2022-07-01 10:47

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=review.models.generate_filename)),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
    ]
