# Generated by Django 4.0.5 on 2022-07-01 19:05

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(null=True, upload_to=review.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
