# Generated by Django 4.0.5 on 2022-07-01 20:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to=home.models.generate_filename)),
                ('image2', models.ImageField(null=True, upload_to=home.models.generate_filename)),
                ('image3', models.ImageField(null=True, upload_to=home.models.generate_filename)),
                ('image4', models.ImageField(null=True, upload_to=home.models.generate_filename)),
            ],
        ),
    ]
